# Generated by Django 4.2.4 on 2023-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0014_chatroom_members_alter_chatroom_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
