# Generated by Django 4.2.4 on 2023-08-29 20:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0016_alter_message_chat_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('date_started', models.DateTimeField(default=datetime.datetime(2023, 8, 29, 23, 53, 45, 735345))),
                ('date_ended', models.DateTimeField(default=datetime.datetime(2023, 8, 29, 23, 53, 45, 735355))),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callee', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
