# Generated by Django 4.2.4 on 2023-08-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_alter_otp_first_name_alter_otp_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
